from __future__ import annotations

from pathlib import Path
import subprocess

from .config import AppConfig


def render_biliup_config(config: AppConfig) -> str:
    lines = [
        "# Generated by douyin-marker.",
        "# Check biliup's current docs if an upstream release changes config keys.",
        "",
    ]
    for streamer in config.streamers:
        lines.extend(
            [
                f'[streamers."{_escape_toml_key(streamer.name)}"]',
                f'url = ["{_escape_toml_string(streamer.url)}"]',
                'tags = ["douyin", "live-recording"]',
                "",
            ]
        )
    return "\n".join(lines)


def write_biliup_config(config: AppConfig, path: str | Path | None = None) -> Path:
    output_path = Path(path or config.biliup.config_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_biliup_config(config), encoding="utf-8")
    return output_path


def run_biliup(config: AppConfig, biliup_config_path: str | Path | None = None) -> int:
    command = [config.biliup.command, *config.biliup.args]
    return subprocess.call(command)


def _escape_toml_key(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _escape_toml_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
